---
# Course Analytics - Provided through K20 LTI App
analytics_2:
  state: hidden
  applies_to: Course
  display_name: New Course and User Analytics
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/New-Analytics-Users/gh-p/analytics">\1</a>
    new_analytics_description: Show new analytics for course and user data. Data
      may take 24 hours to appear in New Analytics after setting this feature flag
      to ON. For full details, please see the *New Analytics user group* in the Canvas
      Community.
  after_state_change_proc: analytics_2_after_state_change_hook
  beta: false
attendance_on_dap_model:
  state: hidden
  applies_to: Account
  display_name: Attendance on DAP
  description:
    attendance_on_dap_model_description: Enable attendance on looker_canvas_attendance on DAP data
  root_opt_in: true
  beta: true
  shadow: true

# Admin Analytics - Provided through K20 LTI App
admin_analytics_view_permission:
  state: hidden
  applies_to: Account
  display_name: Admin Analytics - View admin analytics permission
  description:
    admin_analytics_view_permission_description: Makes the new Admin Analytics permission visible.
  root_opt_in: true
  beta: true
admin_analytics:
  state: allowed
  applies_to: Account
  display_name: Admin Analytics
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Admin-Analytics-Hub/gh-p/admin_analytics">\1</a>
    admin_analytics_description: Enables Analytics at the account-level. Admin Analytics dashboards provide
      details on Canvas usage, Canvas course success, and student engagement.
      Learn more in the *Admin Analytics Hub* in the Canvas community.
  after_state_change_proc: analytics_2_after_state_change_hook
  root_opt_in: true
  beta: false
admin_analytics_dap_model:
  state: hidden
  applies_to: Account
  display_name: Admin Analytics DAP
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Admin-Analytics-Hub/gh-p/admin_analytics">\1</a>
    admin_analytics_dap_model_description: Enables the use of DAP for Analytics at the account-level.
  root_opt_in: true
  beta: true
  shadow: true
course_analytics_dap_model:
  state: hidden
  applies_to: Account
  display_name: New/Course Analytics DAP
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Admin-Analytics-Hub/gh-p/admin_analytics">\1</a>
    admin_analytics_dap_model_description: Enables the use of DAP for Analytics at the account-level.
  root_opt_in: true
  beta: true
  shadow: true

# Intelligent Insights - Provided through K20 LTI App
k20_course_readiness:
  state: hidden
  applies_to: Account
  display_name: Intelligent Insights - Course Readiness
  description:
    k20_course_readiness: Enables the Intelligent Insights - Course Readiness feature and accompanying permission.
  root_opt_in: true
  beta: true
  shadow: true
k20_students_in_need_of_attention:
  state: hidden
  applies_to: Account
  display_name: Intelligent Insights - Students in Need of Attention
  description:
    k20_students_in_need_of_attention: Enables the Intelligent Insights - Students in Need of Attention feature and accompanying permission.
  root_opt_in: true
  beta: true
  shadow: true
k20_lti_usage:
  state: hidden
  applies_to: Account
  display_name: Intelligent Insights - LTI Usage Dashboard
  description:
    k20_lti_usage:  Enables the LTI Usage Dashboard and accompanying permission.
  root_opt_in: true
  beta: true
  shadow: true
k20_lti_insights:
  state: hidden
  applies_to: Account
  display_name: Intelligent Insights - LTI Insights
  description:
    k20_lti_insights: Enables the Intelligent Insights - LTI Insights feature and accompanying permission.
  root_opt_in: true
  beta: true
  shadow: true
  environments:
    ci:
      state: allowed_on
    development:
      state: allowed_on

# Intelligent Insights - Provided through Ask Your Data LTI App
advanced_analytics_ask_questions:
  state: hidden
  applies_to: Account
  display_name: Intelligent Insights - Ask Your Data
  description:
    advanced_analytics_ask_questions: Enables the Intelligent Insights - Ask Your Data feature and accompanying permission.
  root_opt_in: true
  beta: true
  shadow: true

# Analytics Hub
analytics_hub:
  state: hidden
  applies_to: Account
  display_name: "Analytics Hub"
  description: This feature provides a new Analytics Hub platform experience.
  root_opt_in: true
  beta: true
  shadow: true
  environments:
    ci:
      state: allowed_on
    development:
      state: allowed_on
