---
assignment_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Saved)
  description: Updates to the Teacher saved view of assignments.
assignment_edit_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Create/Edit)
  description: Updates to the Teacher create/edit view of assignments.
assign_to_differentiation_tags:
  state: hidden
  applies_to: Account
  shadow: true
  display_name: Assign to Differentiation Tags
  description: Allows instructors to assign course content to differentiation tags via Account/Sub-account setting.
differentiation_tags:
  state: hidden
  applies_to: Course
  display_name: Differentiation Tags
  description: Differentiation Tags allows instructors to create groups of enrolled users that can be used to assign course content.
self_signup_deadline:
  state: hidden
  applies_to: Account
  display_name: Self Sign-up Group Deadline
  description: Allows teachers to set a deadline for students to sign up for a group within a group set.
