---
ags_scores_multiple_files:
  state: hidden
  display_name: Allow multiple file AGS submissions to count as only one submission
  description: |-
    This feature makes it so that when multiple files are submitted together by
    a third party tool via the Assignments and Grade Service API they will be
    grouped as one submission, rather than creating multiple separate submissions.
  applies_to: RootAccount
  environments:
    development:
      state: on
assignment_edit_placement_not_on_announcements:
  state: hidden
  applies_to: SiteAdmin
  display_name: Prevents LTI tools with assignment_edit placement from being launched on Announcements page
  description: When enabled, an LTI tool with the assignment_edit placement will not be launched on the Announcement page.
assignment_submission_type_card:
  state: hidden
  applies_to: SiteAdmin
  display_name: Allow submission type resource card to be shown in the assignment edit page
  description: When enabled, the new submission type resource card will be shown in the assignment edit page.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
disable_graphql_authentication:
  state: hidden
  display_name: Disable authentication for GraphQL
  description: |-
    If enabled, GraphQL queries will not require
    users to be signed in or use an access token.
  applies_to: SiteAdmin
disable_oembed_retrieve:
  state: hidden
  applies_to: RootAccount
  display_name: Disable oembed_retrieve endpoint
  description: |-
    If enabled, the deprecated oembed_retrieve endpoint will be unavailable.
    This is to ease transitioning any potential users off this endpoint before
    removing it altogether.
  shadow: true
disallow_null_custom_variables:
  state: hidden
  applies_to: SiteAdmin
  display_name: Disallow all null values for custom variables
  description: |-
    When enabled, any custom variables that have previously been returning NULL
    will now return the name of the custom variable.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
external_tool_drawer:
  state: hidden
  applies_to: RootAccount
  display_name: External Tool Drawer
  description: Enables experimental external tool drawer layout.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
import_numeric_lti_custom_params_as_string:
  state: hidden
  shadow: true
  applies_to: SiteAdmin
  display_name: Copy numeric lti custom params as strings on imports.
  description: Prevent ResourceLink custom parameters from being converted to numbers during course copy.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_ags_remove_top_submitted_at:
  state: hidden
  applies_to: RootAccount
  shadow: true
  display_name: Remove top-level submittedAt from LTI AGS Score API
  description: |-
    When enabled, removes support for passing submittedAt as a top-level parameter in an
    LTI AGS Score request, to better conform to LTI AGS spec.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_apps_page_instructors:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Page for Instructors
  description: When enabled, the LTI Apps page will be available in the Course navigation sidebar.
  environments:
    development:
      state: hidden
lti_asset_processor:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Enable tools to use Asset Processor-related services and placements
  description: |-
    This feature enables LTI tools to create Asset Processors and use services and placements associated
    with the 1EdTech Asset Processor specifications.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_before_assignment_results:
  state: hidden
  display_name: Display LTI placement before assignment description after submitting.
  description: |-
    If enabled, the assignment_view LTI placement iframe will be shown above the assignment description if the student has a submission
    and can view the assignment. This can be used to make the placement more prominent for tools that require action after an assignment
    has been submitted.
  applies_to: RootAccount
lti_deep_linking_line_items:
  state: hidden
  display_name: LTI Deep Linking Line Items
  description: If enabled, creates assignments from LineItems in deep link messages.
  applies_to: RootAccount
lti_deep_linking_module_index_menu_modal:
  state: hidden
  display_name: LTI Deep Linking for Module Index Menu
  description: If enabled, allows deep linking from the module index via a modal.
  applies_to: RootAccount
lti_deployment_id_in_login_request:
  state: hidden
  applies_to: RootAccount
  display_name: Send lti_deployment_id in the LTI login request
  description: |-
    When enabled the lti_deployment_id will be sent in the LTI 1.3 login request.
    When disabled both deployment_id and lti_deployment_id will be sent.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_find_external_tool_prefer_original_client_id:
  state: hidden
  applies_to: RootAccount
  display_name: Prefer LTI tools with a matching client ID when finding an external tool
  description: |-
    When possible, the LTI tool finding logic will prefer tools installed from the same
    developer key as the original tool. This prevents the edge case where multiple developer
    keys share the same domain, and a tool from the wrong developer key would be matched first.
lti_log_launches:
  state: hidden
  applies_to: RootAccount
  display_name: Log LTI launches
  shadow: true
  description: |-
    When enabled for an account, sends data for all LTI launches to the PandataEvents system
    for querying and visualization. Requires Log LTI launches (Site Admin) to also be enabled.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_log_launches_site_admin:
  state: hidden
  applies_to: SiteAdmin
  display_name: Log LTI launches (Site Admin)
  shadow: true
  description: |-
    Allows for quickly enabling or disabling LTI launch logging while rolling out
    at the account level.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_login_required_error_page:
  state: hidden
  applies_to: SiteAdmin
  display_name: Friendly Error Page for LTI Login Required
  description: |-
    When enabled, a friendly error page will be shown to users when they attempt to launch an LTI tool but encounter the
    dreaded Heisenbug caused by missing cookies. See INTEROP-8200 for more background info.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_migration_info:
  state: hidden
  display_name: LTI 1.1 to 1.3 Migration Info
  shadow: true
  description: When enabled, allows users to view LTI 1.1 to 1.3 migration info on the External Apps page.
  applies_to: RootAccount
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_oidc_missing_cookie_retry:
  state: hidden
  applies_to: RootAccount
  display_name: Retry LTI OIDC launches that fail due to missing cookies
  description: |-
    If enabled, Canvas will retry LTI OIDC launches that fail due to missing cookies.
    Safari tracking protection sometimes blocks cookies from being set to authorize the endpoint.
    To fix this, we resubmit the request with a form.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_placement_restrictions:
  state: hidden
  applies_to: RootAccount
  display_name: Limit certain LTI placements to authorized tools
  description: |-
    When enabled, Submission_type_selection placement usage will be
    limited with an allow list.
  shadow: true
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_registrations_discover_page:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Discover Page
  description: When enabled, the LTI Apps Discover page will be available in the Apps page.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
  custom_transition_proc: lti_registrations_discover_page_hook
lti_registrations_next:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Page Features In-Development
  description: When enabled, the LTI Apps page will have features that are currently in-development.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_registrations_page:
  state: hidden
  beta: true
  applies_to: RootAccount
  display_name: LTI Apps Page
  description: When enabled, the LTI Apps page will be available in the Account navigation sidebar..
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_report_multiple_schema_validation_errors:
  state: hidden
  shadow: true
  applies_to: SiteAdmin
  display_name: Return multiple json schema validation errors at once (not just the first one).
  description: INTEROP-8899. This is a low risk change, because tools should not depend on error messages coming from json schema validator.
  environments:
    ci:
      state: allowed_on
    test:
      state: allowed_on
    development:
      state: allowed_on
    production:
      state: allowed_on
lti_resource_link_id_speedgrader_launches_reference_assignment:
  state: hidden
  applies_to: RootAccount
  display_name: Make SpeedGrader LTI submission launches use assignment (not tool) resource_link_id
  description: |-
    When enabled, LTI 1.1 SpeedGrader launches will set the resource_link_id and
    resource_link_title to the assignment opaque identifier and assignment
    title. With the feature flag off, in SpeedGrader launches, resource_link_id
    and resource_link_title reference the tool (not the assignment) for
    non-NewQuizzes LTI 1.1 tools.
lti_resource_links_api:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Allow LTI 1.3 Resource Links API
  description: |-
    When enabled, the Canvas API for LTI Resource Links is usable. Admins can
    use this API for visibility into content returned from tools.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_toggle_placements:
  state: hidden
  applies_to: RootAccount
  display_name: Allow LTI Placement Toggling
  description: |-
    When enabled, admins can enable or disable existing placements for any
    LTI tool installed on the External Apps page (previously only allowed
    for 1.1 tools to assist with migration to 1.3). Changes to placement
    status for 1.3 tools made on this page will be reset by any changes to the LTI
    developer key, including changes made by Instructure to global inherited keys.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_tools_from_federated_parents:
  state: hidden
  display_name: Show LTI tools from federated parent accounts
  description: |-
    If enabled, LTI tools installed in federated parent accounts will be
    available / visible in child accounts.
  applies_to: SiteAdmin
lti_variable_expansions_use_group_course_as_course:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: "LTI Variable Expansions: Use Group's Course as Course"
  description: >-
    If enabled, if an LTI tool is launched in the context of Course-based Group (Group within a Course), Course-related LTI variable expansions will use
    the Group's Course as the Course. If disabled, legacy behavior will apply -- Course-related LTI variable expansions will only apply when the Course
    is the direct context of the launch.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
microsoft_group_enrollments_syncing:
  state: hidden
  display_name: Microsoft Group enrollment syncing
  description: |-
    If enabled, syncing course enrollments to Microsoft Groups will be
    available. Account admins may enable this in account settings.
  applies_to: RootAccount
platform_notification_service:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Enable Platform Notification Service
  description: >-
    When on, 1Edtech Platform Notification service (used to subscribe tools for notices, list existing notice handlers, notify subscribed tools, etc.) will
    be enabled.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
refactor_custom_variables:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Refactor custom variables to make substitution controllerless.
  description: |-
    Some of the custom variables used a controller instance for substitution.
    That is not available in background jobs, so in PNS notices and content migration.
    This feature flag will refactor the custom variables to make most if the variable substitutions controllerless.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
remove_submission_type_selection_from_dev_keys_edit_page:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Remove submission_type_selection from Dev Keys edit page UI
  description: |-
    When enabled, the submission_type_selection placement will not show up in
    the UI for Dev Keys which do not already have it. Tools can still have the
    placement by editing the JSON, and it will still show up for Dev Keys which
    already have it. This flag is to be removed when after it is completely
    turned on in roughly April-May 2024.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
remove_unwanted_lti_validation_claims:
  state: hidden
  applies_to: SiteAdmin
  display_name: Do not include validation_context and errors claims in LTI Launches
  description: If enabled, the unwanted LTI validation claims like validation_context and errors will not be included in every LTI launch.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
require_permission_for_app_center_token:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Require Manage LTI permissions to set External App Center token
  description: |-
    When enabled, requires any of the manage_lti_* permissions to see the
    Manage App List button on the External Apps page and to update the token
    from Eduappcenter, to prevent accidental changes to the app list.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
top_navigation_placement:
  state: hidden
  applies_to: RootAccount
  display_name: Top Navigation Placement
  description: Enables top_navigation LTI placement. (LTI 1.3 Only)
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
tune_lti_context_id_history_query:
  state: hidden
  applies_to: RootAccount
  display_name: Use alternate settings for LTI Context.id.history query
  description: |-
    In some accounts with a large number of content migrations, the query
    that populates the Context.id.history LTI variable expansion may
    time out regardless of the length of the history for that context.
    Enabling this will run the query with different settings that may
    improve performance. Caution: for some accounts where this query
    doesn't already time out, enabling this may cause the query to take
    much longer and even time out.
update_unified_tool_id:
  state: hidden
  applies_to: RootAccount
  display_name: Fetch Unified Tool ID from LP and update it
  shadow: true
  description: |-
    When enabled, it fetches the unified_tool_id from LearnPlatform and updates the
    unified_tool_id field every time the ContextExternalTool is saved.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
